import type { ChannelType } from './types'
export interface ChannelConfig { type: ChannelType; label: string; shortLabel: string; color: string; bg: string; border: string; description: string; participants: string[]; canSeeCosts: boolean; canSeeInternal: boolean; canSeeCustomerInfo: boolean }
export const CHANNEL_CONFIG: Record<ChannelType, ChannelConfig> = {
  main: { type: 'main', label: 'Main', shortLabel: 'Main', color: 'text-blue-700', bg: 'bg-blue-100', border: 'border-blue-200', description: 'Workspace summary and coordination.', participants: ['Owner', 'Manager', 'PM', 'AI'], canSeeCosts: true, canSeeInternal: true, canSeeCustomerInfo: true },
  customer: { type: 'customer', label: 'Customer', shortLabel: 'Cust', color: 'text-cyan-700', bg: 'bg-cyan-100', border: 'border-cyan-200', description: 'Customer-facing communication.', participants: ['Customer', 'Sales', 'PM', 'AI'], canSeeCosts: false, canSeeInternal: false, canSeeCustomerInfo: true },
  crew: { type: 'crew', label: 'Crew', shortLabel: 'Crew', color: 'text-amber-700', bg: 'bg-amber-100', border: 'border-amber-200', description: 'Daily field communication.', participants: ['Crew', 'Foreman', 'PM', 'AI'], canSeeCosts: false, canSeeInternal: false, canSeeCustomerInfo: true },
  supplier: { type: 'supplier', label: 'Supplier', shortLabel: 'Sup', color: 'text-violet-700', bg: 'bg-violet-100', border: 'border-violet-200', description: 'Material ordering and delivery.', participants: ['Purchasing', 'Supplier', 'AI'], canSeeCosts: true, canSeeInternal: false, canSeeCustomerInfo: false },
  finance: { type: 'finance', label: 'Finance', shortLabel: 'Fin', color: 'text-rose-700', bg: 'bg-rose-100', border: 'border-rose-200', description: 'Job costing and profitability.', participants: ['Owner', 'Managers', 'Accounting', 'AI'], canSeeCosts: true, canSeeInternal: false, canSeeCustomerInfo: true },
  management: { type: 'management', label: 'Management', shortLabel: 'Mgmt', color: 'text-slate-700', bg: 'bg-slate-200', border: 'border-slate-300', description: 'Private to owner/managers.', participants: ['Owner', 'Managers', 'AI'], canSeeCosts: true, canSeeInternal: true, canSeeCustomerInfo: true },
  sales: { type: 'sales', label: 'Sales', shortLabel: 'Sales', color: 'text-orange-700', bg: 'bg-orange-100', border: 'border-orange-200', description: 'Sales coordination.', participants: ['Sales', 'Manager', 'AI'], canSeeCosts: true, canSeeInternal: true, canSeeCustomerInfo: true },
  insurance: { type: 'insurance', label: 'Insurance', shortLabel: 'Ins', color: 'text-cyan-700', bg: 'bg-cyan-100', border: 'border-cyan-200', description: 'Insurance claim communication.', participants: ['Adjuster', 'PM', 'AI'], canSeeCosts: false, canSeeInternal: false, canSeeCustomerInfo: true },
}
export const DEFAULT_CHANNELS_BY_WORKSPACE: Record<string, ChannelType[]> = { project: ['main', 'customer', 'crew', 'supplier', 'finance', 'management'], customer: ['main', 'customer', 'sales'], subcontractor: ['main', 'supplier'], supplier: ['main', 'supplier'] }
export function getChannelConfig(type: string): ChannelConfig { return CHANNEL_CONFIG[type as ChannelType] ?? CHANNEL_CONFIG.main }
