import type { JobroloSkill } from '../types'

export const companySetupSkills: JobroloSkill[] = [
  {
    id: 'company-setup',
    name: 'Company Setup',
    category: 'company_setup',
    status: 'active',
    risk: 'medium',
    priority: 92,
    purpose: 'Guide a contractor workspace from account creation into usable company setup without locking normal chat use.',
    whenToUse: ['First-run setup', 'Missing company information', 'Onboarding company/profile questions'],
    allowedRoles: ['owner', 'admin', 'system'],
    requiredContext: ['contractorId'],
    allowedTools: ['get_contractor_profile', 'update_contractor_profile', 'research_contractor_website'],
    approvalRequiredFor: ['legal/footer/company identity changes'],
    decisionRules: [
      'Show completed and missing company fields as a company setup card.',
      'Suggest chat-first prompts for missing fields instead of sending users to a form first.',
      'Do not block normal navigation after account creation; setup is a guided chat, not a lock.',
    ],
    output: { cards: ['company-profile'] },
    failureHandling: ['If setup data is missing, name the missing field and offer the next prompt/action.'],
  },
  {
    id: 'company-profile',
    name: 'Company Profile',
    category: 'company_setup',
    status: 'active',
    risk: 'medium',
    priority: 94,
    purpose: 'Read and update company identity, website, address, license, contact details, document footer, and report disclaimers.',
    whenToUse: ['Company info lookup', 'Company info updates', 'Estimate/invoice/report readiness checks'],
    whenNotToUse: ['Customer/client lookup'],
    triggers: { phrases: ['company info', 'company profile', 'license', 'legal footer', 'website'] },
    allowedRoles: ['owner', 'admin', 'office', 'system'],
    allowedTools: ['get_contractor_profile', 'update_contractor_profile', 'research_contractor_website'],
    approvalRequiredFor: ['legal/footer/company identity changes'],
    decisionRules: [
      'The contractor company is not a customer/client.',
      'Use get_contractor_profile for saved company facts.',
      'When research finds suggestions, ask before saving unless the user explicitly requested an update.',
    ],
    output: { cards: ['company-profile'] },
  },
  {
    id: 'brand-assets',
    name: 'Brand Assets',
    category: 'company_setup',
    status: 'active',
    risk: 'medium',
    priority: 90,
    purpose: 'Route logos, profile images, colors, and brand files to company/user profile assets instead of customer/project files.',
    whenToUse: ['Logo upload', 'Profile photo upload', 'Brand color/image questions', 'Company document branding'],
    whenNotToUse: ['Jobsite damage photos'],
    triggers: { phrases: ['logo', 'profile photo', 'avatar', 'brand'], uploadPurposes: ['company_logo', 'user_avatar'] },
    allowedRoles: ['owner', 'admin', 'office', 'system'],
    allowedTools: ['update_contractor_profile', 'get_contractor_profile'],
    approvalRequiredFor: ['changing company logo or brand assets when ambiguous'],
    decisionRules: [
      'If a file is uploaded after a logo/profile discussion, treat that recent chat as routing context.',
      'Ask before applying a candidate logo/profile image unless uploadPurpose explicitly says company_logo or user_avatar.',
      'Never attach logos or profile photos to a customer/project by default.',
    ],
    output: { cards: ['company-profile', 'user-profile', 'document-file'] },
  },
  {
    id: 'user-profile',
    name: 'User Profile',
    category: 'company_setup',
    status: 'active',
    risk: 'medium',
    priority: 87,
    purpose: 'Manage the logged-in user identity, avatar/profile photo, role hints, personal setup, and user-specific shortcut context without touching company/customer records.',
    whenToUse: ['My profile', 'Profile photo', 'Avatar', 'User icon', 'My role', 'Account photo'],
    whenNotToUse: ['Company logo', 'Customer photo evidence', 'Jobsite damage photos'],
    triggers: { phrases: ['my profile', 'profile photo', 'avatar', 'user icon', 'my role'], uploadPurposes: ['user_avatar'] },
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'project_manager', 'supplement', 'office', 'crew', 'system'],
    approvalRequiredFor: ['role or permission changes'],
    decisionRules: [
      'Profile photos belong to the user profile unless the user clearly says company logo or job photo.',
      'User role/persona can tune shortcuts and guidance but must not bypass role permissions.',
      'If a profile image is uploaded after a profile-photo discussion, ask to apply it instead of attaching it to the active customer/project.',
      'If no profile-update tool is available in the current runtime, explain the missing workflow instead of claiming the profile was updated.',
    ],
    output: { cards: ['user-profile'] },
  },
]
