import type { JobroloSkill } from '../types'

export const corePlatformSkills: JobroloSkill[] = [
  {
    id: 'brain-stem',
    name: 'Brain Stem Context',
    category: 'core_platform',
    status: 'active',
    risk: 'read',
    priority: 94,
    purpose: 'Summarize the active moment — field, upload, Cody, setup, company, customer/project, support, or planning — without replacing database truth.',
    whenToUse: ['Every agent turn with meaningful context', 'When user asks what next', 'When frustration or ambiguous workflow is present'],
    allowedRoles: ['system'],
    decisionRules: [
      'Brain context is situational guidance, not saved fact.',
      'Use brain signals to choose safer next paths and tone, but use tools/database for truth.',
      'Training and development coaching should wait for activity/KPI evidence before making personal performance claims.',
    ],
    outputFormat: 'Compact internal guidance only; do not expose as a separate bot.',
  },
  {
    id: 'command-center',
    name: 'Command Center',
    category: 'core_platform',
    status: 'active',
    risk: 'low',
    priority: 100,
    purpose: 'Keep Jobrolo chat-first: the chat routes work, cards support decisions, and menus stay secondary.',
    whenToUse: ['Any main chat request', 'Shortcut/pill button prompts', 'When deciding whether to answer, ask, or call a tool'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'homeowner', 'crew', 'supplier', 'adjuster', 'realtor', 'system'],
    decisionRules: [
      'If the user asks to do operational work, call a real tool or explain the missing workflow.',
      'Buttons and cards should insert editable prompts or carry explicit structured action metadata.',
      'Never treat navigation as the primary workflow when chat can route the work.',
    ],
    outputFormat: 'Short chat answer plus cards/attachments when structured data exists.',
  },
  {
    id: 'intent-routing',
    name: 'Intent Routing',
    category: 'core_platform',
    status: 'active',
    risk: 'medium',
    priority: 95,
    purpose: 'Select the smallest relevant skill set before tools run so Jobrolo does not rely on a giant prompt blob.',
    whenToUse: ['Every agent turn', 'Ambiguous upload or save requests', 'Tool retry/failure recovery'],
    allowedRoles: ['system'],
    decisionRules: [
      'Resolve intent before selecting tools.',
      'Prefer read-only resolver tools when the user asks what is saved.',
      'If more than one route is plausible, ask one clear question instead of guessing.',
    ],
  },
  {
    id: 'structured-action-context',
    name: 'Structured Action Context',
    category: 'core_platform',
    status: 'active',
    risk: 'medium',
    priority: 90,
    purpose: 'Keep every button, approval, and tool action tied to real record IDs and user-visible meaning.',
    whenToUse: ['Cards', 'Pill buttons', 'Approvals', 'Document actions', 'Chat creation actions'],
    allowedRoles: ['system'],
    decisionRules: [
      'Actions must identify action type, target record, visibility, and whether approval is required.',
      'Never replay approvals using placeholder or guessed IDs.',
      'If a card cannot execute safely, it should insert an editable prompt.',
    ],
    output: { cards: ['approval-action'] },
  },
  {
    id: 'approval',
    name: 'Approval',
    category: 'core_platform',
    status: 'active',
    risk: 'high',
    priority: 100,
    purpose: 'Protect destructive, external, financial, legal, and permission-changing actions.',
    whenToUse: ['Deletes', 'External sends', 'Import/replace pricing', 'Final documents', 'Company profile/legal changes', 'Invites and share links'],
    allowedRoles: ['owner', 'admin', 'system'],
    approvalRequiredFor: ['delete records', 'send externally', 'replace/import pricing', 'finalize/share documents', 'change permissions', 'update legal/company identity fields'],
    decisionRules: [
      'Approval cards must say exactly what will happen and name affected records.',
      'Approval replay must call the pending action tool with a real database ID.',
      'Do not ask for approval twice if a valid pending approval already exists; replay it.',
    ],
    output: { cards: ['approval-action'] },
    failureHandling: ['If approval execution fails, say it failed and include the error/reason.'],
  },
  {
    id: 'communication-routing',
    name: 'Communication Routing',
    category: 'core_platform',
    status: 'active',
    risk: 'external',
    priority: 93,
    purpose: 'Route chat links, invites, SMS/email drafts, customer updates, crew messages, and external notifications through safe visibility and approval rules.',
    whenToUse: ['Send text', 'Invite person', 'Copy link', 'Customer update', 'Crew message', 'Notify homeowner', 'Email adjuster', 'Get Jobrolo number', 'Company phone/SMS setup'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'project_manager', 'office', 'system'],
    requiredContext: ['recipient type or chat/project context for external sends'],
    optionalContext: ['phone/email', 'message draft', 'link', 'visibility', 'role'],
    allowedTools: ['create_project_chat', 'invite_user_to_chat', 'get_company_phone_numbers', 'search_company_phone_numbers', 'provision_company_phone_number', 'consult_orchestrator'],
    approvalRequiredFor: ['SMS/email sends', 'external invites', 'public/share links', 'provisioning or buying company phone numbers'],
    decisionRules: [
      'Creating a chat, copying a link, inviting a user, and sending a notification are separate actions.',
      'Return a copyable link by default when a shared chat is created.',
      'Do not send SMS/email unless explicitly requested and contact information exists.',
      'Search/list company phone numbers before provisioning a paid Twilio number.',
      'Provisioning a Jobrolo/company phone number requires owner/admin approval.',
      'External messages require recipient, visibility, and approval before sending.',
    ],
    output: { cards: ['shared-chat', 'notification-outbox', 'company-phone-numbers'] },
    outputFormat: 'Communication card with open chat, copy link, invite, draft/send options, company number setup, and visibility labels.',
  },
  {
    id: 'company-phone-number',
    name: 'Company Phone Number',
    category: 'core_platform',
    status: 'active',
    risk: 'external',
    priority: 92,
    purpose: 'Manage company-owned Jobrolo/Twilio numbers for phone sign-in, SMS routing, invites, customer communication, and future company/user dedicated numbers.',
    whenToUse: ['Get Jobrolo number', 'Search company phone numbers', 'Buy/provision Twilio number', 'Phone sign-in setup', 'SMS readiness', 'Company texting number'],
    allowedRoles: ['owner', 'admin', 'project_manager', 'office', 'system'],
    requiredContext: ['contractor/workspace identity'],
    optionalContext: ['area code', 'desired digits', 'purpose', 'A2P status', 'SMS/voice capability'],
    allowedTools: ['get_company_phone_numbers', 'search_company_phone_numbers', 'provision_company_phone_number', 'get_integration_readiness', 'consult_orchestrator'],
    approvalRequiredFor: ['provisioning/buying phone numbers', 'external SMS sends', 'changing company communication routing'],
    decisionRules: [
      'Listing saved numbers and searching available numbers are safe read actions.',
      'Provisioning/buying a number is cost-bearing and must require owner/admin approval.',
      'Do not claim outbound texting is fully ready unless Twilio credentials and business messaging/A2P setup are ready.',
      'Company numbers are company communication infrastructure, not customer phone records.',
      'If user asks to sign in with phone, use phone auth setup; if user asks for a business texting number, use company number setup.',
    ],
    output: { cards: ['company-phone-numbers', 'integration-readiness', 'approval-action'] },
    outputFormat: 'Company phone number card with saved numbers, available candidates, SMS readiness, and approval-gated provisioning prompts.',
  },
  {
    id: 'offline-continuity',
    name: 'Offline Continuity',
    category: 'core_platform',
    status: 'active',
    risk: 'medium',
    priority: 89,
    purpose: 'Preserve field notes, GPS observations, photo evidence, drafts, and lightweight activity while a device has weak/no service, then sync back into Jobrolo truth safely.',
    whenToUse: ['Offline/spotty service', 'Field notes with GPS', 'Photos captured without service', 'Mobile field work', 'AR/glasses capture planning'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'project_manager', 'office', 'system'],
    requiredContext: ['local event type', 'source', 'safe entity refs when available'],
    optionalContext: ['GPS snapshot', 'document/photo id', 'project/customer/workspace context'],
    allowedTools: ['record_field_observation_at_location', 'log_field_action', 'log_canvassing_activity', 'record_property_observation'],
    forbiddenTools: ['create_customer', 'create_project_for_customer', 'import_price_sheet_items'],
    decisionRules: [
      'Local offline cache is display/continuity context; server database records remain the source of truth.',
      'When syncing, preserve event source, GPS accuracy, timestamps, and entity refs so the activity spine can reconstruct what happened.',
      'Do not create customers, projects, invoices, price imports, or external messages from offline cache without explicit confirmation after sync.',
      'If offline evidence conflicts with server truth, surface a conflict instead of overwriting records.',
    ],
    output: { cards: ['activity-timeline', 'evidence-intake', 'field-map'] },
    failureHandling: [
      'If sync is unavailable, keep the event pending and tell the user it is saved locally, not in Jobrolo records yet.',
      'If an offline event has no project/customer context, acknowledge it only and ask where to attach after connection returns.',
    ],
  },
  {
    id: 'role-permissions',
    name: 'Role Permissions',
    category: 'core_platform',
    status: 'active',
    risk: 'high',
    priority: 92,
    purpose: 'Keep owner/admin, employee, sales, PM, crew/sub, homeowner, adjuster, realtor, and supplier access boundaries clear.',
    whenToUse: ['Invite user', 'Permission', 'Role', 'Who can see this?', 'Subcontractor access', 'Homeowner access'],
    allowedRoles: ['owner', 'admin', 'system'],
    approvalRequiredFor: ['role changes', 'workspace membership changes', 'external access grants'],
    decisionRules: [
      'Subs/crews should only see assigned chats/jobs/files.',
      'Homeowners and partners only see explicitly shared customer-facing content.',
      'Owners/admins can manage users; non-admin roles cannot delete company/project chats by default.',
      'If the role or scope is unclear, ask before creating access.',
    ],
    output: { cards: ['permission-access'] },
  },
  {
    id: 'failure-handling',
    name: 'Failure Handling',
    category: 'core_platform',
    status: 'active',
    risk: 'high',
    priority: 100,
    purpose: 'Stop fake progress and clearly separate planned, pending, failed, and completed work.',
    whenToUse: ['Every tool failure', 'Narrated action without tools', 'Missing workflow/tool situations'],
    allowedRoles: ['system'],
    decisionRules: [
      'Only say saved/created/updated/deleted/imported after a successful tool/database result.',
      'If no tool exists, name the missing workflow instead of pretending.',
      'If tool args are placeholders or filenames-as-content, block and reroute.',
    ],
    output: { cards: ['operations-radar'] },
  },
]
