import type { JobroloSkill } from '../types'

export const corePlatformSkills: JobroloSkill[] = [
  {
    id: 'command-center',
    name: 'Command Center',
    category: 'core_platform',
    status: 'active',
    risk: 'low',
    priority: 100,
    purpose: 'Keep Jobrolo chat-first: the chat routes work, cards support decisions, and menus stay secondary.',
    whenToUse: ['Any main chat request', 'Shortcut/pill button prompts', 'When deciding whether to answer, ask, or call a tool'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'homeowner', 'crew', 'supplier', 'adjuster', 'realtor', 'system'],
    decisionRules: [
      'If the user asks to do operational work, call a real tool or explain the missing workflow.',
      'Buttons and cards should insert editable prompts or carry explicit structured action metadata.',
      'Never treat navigation as the primary workflow when chat can route the work.',
    ],
    outputFormat: 'Short chat answer plus cards/attachments when structured data exists.',
  },
  {
    id: 'intent-routing',
    name: 'Intent Routing',
    category: 'core_platform',
    status: 'active',
    risk: 'medium',
    priority: 95,
    purpose: 'Select the smallest relevant skill set before tools run so Jobrolo does not rely on a giant prompt blob.',
    whenToUse: ['Every agent turn', 'Ambiguous upload or save requests', 'Tool retry/failure recovery'],
    allowedRoles: ['system'],
    decisionRules: [
      'Resolve intent before selecting tools.',
      'Prefer read-only resolver tools when the user asks what is saved.',
      'If more than one route is plausible, ask one clear question instead of guessing.',
    ],
  },
  {
    id: 'structured-action-context',
    name: 'Structured Action Context',
    category: 'core_platform',
    status: 'active',
    risk: 'medium',
    priority: 90,
    purpose: 'Keep every button, approval, and tool action tied to real record IDs and user-visible meaning.',
    whenToUse: ['Cards', 'Pill buttons', 'Approvals', 'Document actions', 'Chat creation actions'],
    allowedRoles: ['system'],
    decisionRules: [
      'Actions must identify action type, target record, visibility, and whether approval is required.',
      'Never replay approvals using placeholder or guessed IDs.',
      'If a card cannot execute safely, it should insert an editable prompt.',
    ],
  },
  {
    id: 'approval',
    name: 'Approval',
    category: 'core_platform',
    status: 'active',
    risk: 'high',
    priority: 100,
    purpose: 'Protect destructive, external, financial, legal, and permission-changing actions.',
    whenToUse: ['Deletes', 'External sends', 'Import/replace pricing', 'Final documents', 'Company profile/legal changes', 'Invites and share links'],
    allowedRoles: ['owner', 'admin', 'system'],
    approvalRequiredFor: ['delete records', 'send externally', 'replace/import pricing', 'finalize/share documents', 'change permissions', 'update legal/company identity fields'],
    decisionRules: [
      'Approval cards must say exactly what will happen and name affected records.',
      'Approval replay must call the pending action tool with a real database ID.',
      'Do not ask for approval twice if a valid pending approval already exists; replay it.',
    ],
    failureHandling: ['If approval execution fails, say it failed and include the error/reason.'],
  },
  {
    id: 'failure-handling',
    name: 'Failure Handling',
    category: 'core_platform',
    status: 'active',
    risk: 'high',
    priority: 100,
    purpose: 'Stop fake progress and clearly separate planned, pending, failed, and completed work.',
    whenToUse: ['Every tool failure', 'Narrated action without tools', 'Missing workflow/tool situations'],
    allowedRoles: ['system'],
    decisionRules: [
      'Only say saved/created/updated/deleted/imported after a successful tool/database result.',
      'If no tool exists, name the missing workflow instead of pretending.',
      'If tool args are placeholders or filenames-as-content, block and reroute.',
    ],
  },
]
