import type { JobroloSkill } from '../types'

export const customersProjectsSkills: JobroloSkill[] = [
  {
    id: 'lead-intake',
    name: 'Lead Intake',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 93,
    purpose: 'Capture potential customer opportunities from calls, texts, door knocks, referrals, online leads, or conversations before converting them into customers/jobs.',
    whenToUse: ['New lead', 'Phone call lead', 'Door knock lead', 'Referral', 'Leak call', 'Conversation at store', 'Potential customer'],
    allowedRoles: ['owner', 'admin', 'sales', 'office', 'system'],
    requiredContext: ['lead source or contact/property details when available'],
    optionalContext: ['homeowner name', 'phone', 'email', 'address', 'source', 'urgency', 'notes', 'requested appointment', 'field map pin', 'browser GPS'],
    allowedTools: ['start_field_inspection_lead', 'create_canvassing_lead_at_location', 'update_canvassing_lead', 'log_canvassing_activity', 'create_customer', 'create_project_for_customer', 'consult_orchestrator'],
    forbiddenTools: ['create_roof_report', 'import_price_sheet_items'],
    approvalRequiredFor: ['converting lead into customer/project', 'sending external follow-up'],
    decisionRules: [
      'Treat new opportunities as leads first unless the user explicitly says to create a customer/job.',
      'Door knocks, map drops, and GPS field pins should stay as canvassing/field leads until converted.',
      'Collect source, contact, address, urgency, notes, and next step in a chat-first way.',
      'If information is missing, save what is known and ask one useful next question.',
      'Do not start an inspection unless the user says inspection or current-location field context is present.',
    ],
    output: { cards: ['lead-intake', 'field-map'] },
    outputFormat: 'Lead intake card with known fields, missing fields, source, next-step pills, and conversion actions.',
  },
  {
    id: 'appointment-scheduling',
    name: 'Appointment Scheduling',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 89,
    purpose: 'Schedule, review, and reason about inspections, adjuster meetings, follow-ups, material deliveries, and production appointments.',
    whenToUse: ['Schedule inspection', 'Book appointment', 'What is on calendar', 'Adjuster meeting', 'Follow-up tomorrow', 'Crew start date'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'project_manager', 'office', 'system'],
    requiredContext: ['date/time or request to find availability', 'customer/project/person when creating appointment'],
    optionalContext: ['location', 'attendees', 'appointment type', 'notes', 'duration', 'field map point', 'browser GPS'],
    allowedTools: ['list_schedule', 'show_calendar', 'create_appointment', 'update_project_schedule', 'resolve_field_location', 'get_canvassing_map', 'consult_orchestrator'],
    approvalRequiredFor: ['sending invites or notifications externally'],
    decisionRules: [
      'Do not confuse starting an inspection now with scheduling a future inspection.',
      'If date/time is missing, ask for the smallest missing scheduling detail.',
      'Tie appointments to customer/project/lead context when available.',
      'Appointments only appear on the field map when they have a saved location ping or resolved address; do not invent coordinates.',
      'When showing a calendar, present a compact card and prompt pills instead of a bulky form.',
    ],
    output: { cards: ['schedule'] },
  },
  {
    id: 'bid-quote',
    name: 'Bid / Quote Workflow',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 91,
    purpose: 'Keep cash quote, bid, proposal, and estimate requests grounded in saved customer/project/address/document context before drafting numbers or documents.',
    whenToUse: ['Create bid', 'Cash quote', 'Draft proposal', 'Research this address for quote', 'Price this job'],
    allowedRoles: ['owner', 'admin', 'sales', 'office', 'system'],
    requiredContext: ['customer or property', 'project/job or explicit new-job intent'],
    optionalContext: ['scope document', 'photos', 'price list', 'labor assumptions'],
    allowedTools: ['get_customer_file', 'list_customers', 'get_project_document_packet', 'get_document_content', 'review_price_sheet_items', 'consult_orchestrator'],
    forbiddenTools: ['start_field_inspection_lead', 'create_roof_report'],
    approvalRequiredFor: ['creating or sending customer-facing proposal documents'],
    decisionRules: [
      'Stay in bid/quote workflow once selected unless the user clearly changes task.',
      'Resolve customer/project/address/files before drafting.',
      'Do not create a lead, inspection, or roof report just because a quote mentions an address.',
      'If a customer/project is ambiguous, ask one concise clarification.',
    ],
    output: { cards: ['cash-quote', 'estimate-proposal', 'job-cost', 'scope-breakdown', 'document-file'] },
  },
  {
    id: 'invoice',
    name: 'Invoice / Payment',
    category: 'customers_projects',
    status: 'active',
    risk: 'high',
    priority: 84,
    purpose: 'Create, review, and explain customer invoices, payment requests, payments received, balances due, and accounts-receivable status from project financial truth.',
    whenToUse: ['Customer invoice', 'Payment request', 'Balance due', 'Record payment', 'Accounts receivable', 'Unpaid invoice'],
    allowedRoles: ['owner', 'admin', 'office', 'project_manager', 'sales', 'system'],
    requiredContext: ['project/customer when creating or recording invoice/payment truth'],
    optionalContext: ['signed contract', 'approved change orders', 'payment terms', 'payment method', 'source document'],
    allowedTools: ['get_project_financial_summary', 'create_project_financial_entry', 'get_project_document_packet', 'consult_orchestrator'],
    approvalRequiredFor: ['creating invoice/payment ledger entries', 'sending invoices or payment links'],
    decisionRules: [
      'Separate customer invoices/payments from supplier invoices/job costs.',
      'Use approved project revenue/payment entries for balance due; do not infer final balance from chat memory.',
      'Ask for missing amount, due date, payment method, or project before creating financial truth.',
      'Sending or sharing customer-facing invoices requires approval.',
    ],
    output: { cards: ['invoice', 'job-cost'] },
    outputFormat: 'Invoice/payment card with amount, balance, due date/status, source document, and approval-safe next actions.',
  },
  {
    id: 'entity-resolver',
    name: 'Entity Resolver',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 100,
    purpose: 'Resolve company/customer/project/document context before any tool call that reads or mutates saved data.',
    whenToUse: ['Customer lookup', 'Project lookup', 'Attach/save/link requests', 'What is saved?'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'system'],
    allowedTools: ['get_customer_file', 'list_customers', 'get_project_document_packet'],
    decisionRules: [
      'Contractor company names are not customers.',
      'When multiple customers/projects match, ask the user to choose.',
      'When the user says saved records only, use DB tools and not chat memory.',
    ],
    output: { cards: ['customer-file'] },
  },
  {
    id: 'customer-creation',
    name: 'Customer Creation',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 86,
    purpose: 'Create customer/client records from explicit customer/contact information.',
    whenToUse: ['Create client/customer', 'Convert lead to customer', 'Save homeowner contact'],
    allowedRoles: ['owner', 'admin', 'sales', 'office', 'system'],
    allowedTools: ['create_customer'],
    decisionRules: [
      'Do not create customers from contractor company names or supplier names.',
      'Use extracted document parties only after conflict checks or user confirmation.',
    ],
    output: { cards: ['customer-file', 'lead-intake'] },
  },
  {
    id: 'project-creation',
    name: 'Project Creation',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 88,
    purpose: 'Create jobs/projects linked to a resolved customer with project number, address, stage, value, and scope context.',
    whenToUse: ['Create project/job', 'Create job from document', 'Convert lead to job'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'office', 'system'],
    allowedTools: ['create_project_for_customer', 'create_project_from_document'],
    decisionRules: [
      'Resolve customer first; ask/create customer if missing.',
      'If a document conflicts with an existing customer, ask before linking.',
      'Use real customerId/projectId in approval cards and tool calls.',
    ],
    output: { cards: ['customer-file', 'shared-chat'] },
  },
  {
    id: 'project-context',
    name: 'Project Context',
    category: 'customers_projects',
    status: 'active',
    risk: 'low',
    priority: 92,
    purpose: 'Maintain the active customer/project context for later chat turns and card actions.',
    whenToUse: ['Current customer/project references', 'This job/file/project', 'Crew or report actions'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'crew', 'system'],
    allowedTools: ['get_customer_file', 'get_project_document_packet'],
    decisionRules: [
      'Prefer the current workspace project when the chat is already in a project chat.',
      'Do not call project tools with null projectId.',
      'If active context is stale or ambiguous, ask one concise clarification.',
    ],
    output: { cards: ['customer-file', 'production-status'] },
  },
  {
    id: 'project-status',
    name: 'Project Status',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 82,
    purpose: 'Track and explain project stage, readiness, next steps, tasks, approvals, documents, and timeline.',
    whenToUse: ['What is next?', 'Job status', 'What needs approval?', 'What is on my plate?'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'office', 'system'],
    decisionRules: [
      'Ground status in saved projects, tasks, approvals, documents, and activity logs.',
      'Do not call a job ready to build unless saved requirements, approvals, material status, schedule, and customer-facing blockers are checked.',
      'If readiness data is missing, say what is missing instead of guessing.',
    ],
    output: { cards: ['production-status', 'operations-radar'] },
    outputFormat: 'Compact readiness/status card with blockers, ready items, next actions, and source labels from saved records.',
  },
]
