import type { JobroloSkill } from '../types'

export const customersProjectsSkills: JobroloSkill[] = [
  {
    id: 'bid-quote',
    name: 'Bid / Quote Workflow',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 91,
    purpose: 'Keep cash quote, bid, proposal, and estimate requests grounded in saved customer/project/address/document context before drafting numbers or documents.',
    whenToUse: ['Create bid', 'Cash quote', 'Draft proposal', 'Research this address for quote', 'Price this job'],
    allowedRoles: ['owner', 'admin', 'sales', 'office', 'system'],
    requiredContext: ['customer or property', 'project/job or explicit new-job intent'],
    optionalContext: ['scope document', 'photos', 'price list', 'labor assumptions'],
    allowedTools: ['get_customer_file', 'list_customers', 'get_project_document_packet', 'get_document_content', 'review_price_sheet_items', 'consult_orchestrator'],
    forbiddenTools: ['start_field_inspection_lead', 'create_roof_report'],
    approvalRequiredFor: ['creating or sending customer-facing proposal documents'],
    decisionRules: [
      'Stay in bid/quote workflow once selected unless the user clearly changes task.',
      'Resolve customer/project/address/files before drafting.',
      'Do not create a lead, inspection, or roof report just because a quote mentions an address.',
      'If a customer/project is ambiguous, ask one concise clarification.',
    ],
  },
  {
    id: 'entity-resolver',
    name: 'Entity Resolver',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 100,
    purpose: 'Resolve company/customer/project/document context before any tool call that reads or mutates saved data.',
    whenToUse: ['Customer lookup', 'Project lookup', 'Attach/save/link requests', 'What is saved?'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'system'],
    allowedTools: ['get_customer_file', 'list_customers', 'get_project_document_packet'],
    decisionRules: [
      'Contractor company names are not customers.',
      'When multiple customers/projects match, ask the user to choose.',
      'When the user says saved records only, use DB tools and not chat memory.',
    ],
  },
  {
    id: 'customer-creation',
    name: 'Customer Creation',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 86,
    purpose: 'Create customer/client records from explicit customer/contact information.',
    whenToUse: ['Create client/customer', 'Convert lead to customer', 'Save homeowner contact'],
    allowedRoles: ['owner', 'admin', 'sales', 'office', 'system'],
    allowedTools: ['create_customer'],
    decisionRules: [
      'Do not create customers from contractor company names or supplier names.',
      'Use extracted document parties only after conflict checks or user confirmation.',
    ],
  },
  {
    id: 'project-creation',
    name: 'Project Creation',
    category: 'customers_projects',
    status: 'active',
    risk: 'medium',
    priority: 88,
    purpose: 'Create jobs/projects linked to a resolved customer with project number, address, stage, value, and scope context.',
    whenToUse: ['Create project/job', 'Create job from document', 'Convert lead to job'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'office', 'system'],
    allowedTools: ['create_project_for_customer', 'create_project_from_document'],
    decisionRules: [
      'Resolve customer first; ask/create customer if missing.',
      'If a document conflicts with an existing customer, ask before linking.',
      'Use real customerId/projectId in approval cards and tool calls.',
    ],
  },
  {
    id: 'project-context',
    name: 'Project Context',
    category: 'customers_projects',
    status: 'active',
    risk: 'low',
    priority: 92,
    purpose: 'Maintain the active customer/project context for later chat turns and card actions.',
    whenToUse: ['Current customer/project references', 'This job/file/project', 'Crew or report actions'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'crew', 'system'],
    allowedTools: ['get_customer_file', 'get_project_document_packet'],
    decisionRules: [
      'Prefer the current workspace project when the chat is already in a project chat.',
      'Do not call project tools with null projectId.',
      'If active context is stale or ambiguous, ask one concise clarification.',
    ],
  },
  {
    id: 'project-status',
    name: 'Project Status',
    category: 'customers_projects',
    status: 'planned',
    risk: 'medium',
    priority: 70,
    purpose: 'Track and explain project stage, readiness, next steps, tasks, approvals, documents, and timeline.',
    whenToUse: ['What is next?', 'Job status', 'What needs approval?', 'What is on my plate?'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'office', 'system'],
    decisionRules: ['Ground status in saved projects, tasks, approvals, documents, and activity logs.'],
  },
]
