import type { JobroloSkill } from '../types'

export const productionSkills: JobroloSkill[] = [
  {
    id: 'roof-report',
    name: 'Roof / Property Report',
    version: '0.1.0',
    category: 'production',
    status: 'active',
    risk: 'medium',
    priority: 87,
    purpose: 'Create and refine roof/property reports from selected photos, conditions, captions, recommendations, company branding, and share targets.',
    whenToUse: ['Roof report', 'Property report', 'Damage report', 'Add photos to report', 'Preview report', 'Share report'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'project_manager', 'office', 'system'],
    requiredContext: ['customer/project or report draft when editing a report'],
    optionalContext: ['selected photos', 'conditions', 'recommendations', 'recipient type', 'company branding'],
    allowedTools: ['create_roof_report', 'get_project_document_packet', 'review_roof_report_photos', 'add_photos_to_roof_report', 'update_roof_report_photo_selection', 'finalize_roof_report', 'consult_orchestrator'],
    forbiddenTools: ['import_price_sheet_items'],
    approvalRequiredFor: ['finalizing or sharing customer-facing reports', 'external report links'],
    decisionRules: [
      'Reports should be finished in chat/cards, not by dumping users into a bulky builder first.',
      'Ask users which photos belong in the report and allow removal/editing before finalizing.',
      'Do not finalize or share until required photos/sections are complete and approval is given.',
      'Recipient matters: homeowner, crew/sub, adjuster, realtor, and internal report views require different visibility.',
    ],
    output: { cards: ['roof-report', 'photo-evidence', 'external-share'] },
    outputFormat: 'Report card with readiness, selected photos, missing sections, preview/share/finalize prompt actions.',
  },
  {
    id: 'insurance-claim',
    name: 'Insurance Claim / Supplement',
    version: '0.1.0',
    category: 'production',
    status: 'active',
    risk: 'medium',
    priority: 86,
    purpose: 'Organize insurance claim facts, estimate/scope financials, supplement opportunities, deductible math, adjuster context, and claim document gaps.',
    whenToUse: ['Insurance claim', 'Supplement', 'Deductible', 'RCV', 'ACV', 'Depreciation', 'Adjuster estimate', 'Mortgage check'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'project_manager', 'supplement', 'supplementer', 'office', 'system'],
    requiredContext: ['customer/project or claim document context'],
    optionalContext: ['claim number', 'carrier', 'adjuster', 'scope analysis', 'photos', 'mortgage company', 'deductible'],
    allowedTools: ['get_customer_file', 'get_project_document_packet', 'get_scope_breakdown', 'consult_orchestrator'],
    forbiddenTools: ['send_external_message', 'finalize_roof_report'],
    approvalRequiredFor: ['customer-facing claim messages', 'adjuster/carrier sends', 'saving supplement tasks'],
    decisionRules: [
      'Separate saved claim facts from inferred supplement opportunities.',
      'Do not claim coverage, liability, or legal conclusions.',
      'Use saved scope/photo/document records before suggesting claim gaps.',
      'Ask for project/customer context if the claim target is ambiguous.',
    ],
    output: { cards: ['insurance-claim', 'scope-breakdown', 'photo-evidence'] },
    outputFormat: 'Insurance claim card with saved financials, missing claim data, document gaps, and supplement next-step prompts.',
  },
  {
    id: 'field-copilot',
    name: 'Field Copilot',
    version: '0.1.0',
    category: 'production',
    status: 'active',
    risk: 'medium',
    priority: 88,
    purpose: 'Handle field/inspection/location observations as property evidence first, then convert to leads/customers/jobs only after confirmation.',
    whenToUse: ['start inspection', 'where I am', 'roof damage from ground', 'no soliciting sign', 'field observation', 'GPS/photo evidence'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'project_manager', 'system'],
    optionalContext: ['browser GPS', 'active project', 'property memory', 'photo section'],
    allowedTools: ['start_field_inspection_lead', 'record_field_observation_at_location', 'resolve_field_location', 'research_property_now'],
    forbiddenTools: ['create_customer', 'create_project_for_customer'],
    approvalRequiredFor: ['converting field lead into customer/project', 'sending external notifications'],
    decisionRules: [
      'Start inspections as field leads until customer/project is confirmed.',
      'Attach GPS/location context to observations and inspection photos when present.',
      'Do not require homeowner name or phone before starting a field inspection lead.',
      'Ask before converting property observations into real customer/project records.',
    ],
    output: { cards: ['field-inspection', 'photo-evidence'] },
    outputFormat: 'Short field card or next-action prompt tied to location, lead, or project context.',
  },
  {
    id: 'production-coordinator',
    name: 'Production Coordinator',
    version: '0.1.0',
    category: 'production',
    status: 'active',
    risk: 'medium',
    priority: 70,
    purpose: 'Coordinate install-day and production details from chat without pretending external work was completed.',
    whenToUse: ['crew start', 'material drop', 'production update', 'install note', 'tarp flowers', 'protect pool'],
    allowedRoles: ['owner', 'admin', 'project_manager', 'production', 'office', 'system'],
    requiredContext: ['projectId or resolvable project'],
    optionalContext: ['crew chat', 'task due date', 'photos', 'supplier'],
    triggers: {
      phrases: ['crew start', 'material drop', 'production', 'install', 'tarp', 'protect', 'walkthrough'],
    },
    allowedTools: ['get_project_context', 'create_project_chat'],
    approvalRequiredFor: ['external messages', 'subcontractor invites', 'customer-facing updates'],
    decisionRules: [
      'Treat production notes as project timeline/activity unless the user asks to send them externally.',
      'If a crew/sub chat is requested, resolve project and crew/sub role before creating/inviting.',
      'If no send/invite integration is configured, create the draft/link and say what remains manual.',
    ],
    output: { cards: ['production-status', 'shared-chat', 'activity-timeline', 'job-cost', 'material-order'] },
    outputFormat: 'Production card or short next-action list tied to the project.',
    failureHandling: ['If project context is missing, ask which job instead of creating floating tasks.'],
    tests: ['crew note should attach to project context', 'material drop should not create supplier order without approval'],
  },
  {
    id: 'job-cost',
    name: 'Job Cost / Margin',
    version: '0.1.0',
    category: 'production',
    status: 'active',
    risk: 'high',
    priority: 90,
    purpose: 'Maintain the project financial truth sheet: contract/revenue, material cost, labor cost, other costs, payments, commission, profit, and margin.',
    whenToUse: ['Job cost', 'Margin', 'Profit', 'Gross profit', 'COGS', 'Project financials', 'What did we make?', 'Cost to build'],
    allowedRoles: ['owner', 'admin', 'production', 'project_manager', 'office', 'sales', 'system'],
    requiredContext: ['projectId or resolvable project'],
    optionalContext: ['source documents', 'scope analysis', 'supplier invoice', 'labor invoice', 'payment record', 'commission rule'],
    allowedTools: ['get_project_financial_summary', 'create_project_financial_entry', 'get_project_document_packet', 'review_price_sheet_items', 'consult_orchestrator'],
    approvalRequiredFor: ['creating/updating financial ledger entries', 'marking costs paid or payments collected'],
    decisionRules: [
      'Documents are evidence; ProjectFinancialEntry rows are the job financial truth.',
      'Separate proposed, candidate, approved, paid, collected, rejected, and voided numbers.',
      'Do not call margin final if material, labor, commission, or customer payment records are missing.',
      'Use saved financial entries before chat memory when answering money questions.',
    ],
    output: { cards: ['job-cost', 'invoice', 'labor-cost', 'commission', 'material-order'] },
    outputFormat: 'Job cost card with revenue, cost buckets, payments, commission, margin, missing entries, and source evidence.',
    failureHandling: ['If no financial entries exist, show a starter job-cost card with missing inputs and prompt pills.'],
  },
  {
    id: 'project-closeout',
    name: 'Project Closeout',
    version: '0.1.0',
    category: 'production',
    status: 'active',
    risk: 'high',
    priority: 91,
    purpose: 'Verify a project is truly ready to close by checking saved stage, final report/docs, signatures, invoices, payments, job costs, commission, warranty/closeout packet, and unresolved blockers.',
    whenToUse: ['Closeout', 'Close the job', 'Ready to close', 'Final invoice', 'Warranty packet', 'Closeout packet', 'Job complete'],
    allowedRoles: ['owner', 'admin', 'production', 'project_manager', 'office', 'sales', 'system'],
    requiredContext: ['projectId or resolvable project'],
    optionalContext: ['final report', 'signature status', 'invoice/payment records', 'job cost sheet', 'warranty document', 'final walkthrough'],
    allowedTools: ['get_project_context', 'get_project_document_packet', 'get_project_financial_summary', 'list_schedule', 'show_calendar', 'consult_orchestrator'],
    forbiddenTools: ['create_customer', 'create_project_for_customer', 'import_price_sheet_items'],
    approvalRequiredFor: ['changing project stage to closed', 'sending closeout packets', 'creating/updating final financial entries'],
    decisionRules: [
      'Closeout is a readiness checklist, not a generic summary.',
      'Use saved project schedule, documents, roof reports, signatures, activity, and ProjectFinancialEntry rows before saying the job is closed.',
      'Separate ready items, blockers, missing evidence, and approval-required next actions.',
      'Do not mark closeout complete while invoices, payments, job cost, commission, warranty, or final report/signature status is unknown.',
    ],
    output: { cards: ['production-status', 'job-cost', 'activity-timeline', 'document-file'] },
    outputFormat: 'Closeout/readiness card with completed items, blockers, missing records, source evidence, and prompt-first next actions.',
    failureHandling: ['If project context is missing, ask which job to close out before checking anything.'],
  },
  {
    id: 'labor-cost',
    name: 'Labor / Sub Cost',
    version: '0.1.0',
    category: 'production',
    status: 'active',
    risk: 'high',
    priority: 78,
    purpose: 'Track labor and subcontractor quotes, invoices, approvals, and paid status as project cost truth.',
    whenToUse: ['Labor cost', 'Sub invoice', 'Crew cost', 'Installer pay', 'Subcontractor quote'],
    allowedRoles: ['owner', 'admin', 'production', 'project_manager', 'office', 'system'],
    requiredContext: ['project/customer or crew/sub context'],
    optionalContext: ['quote document', 'invoice document', 'crew chat', 'scope of labor'],
    allowedTools: ['get_project_financial_summary', 'create_project_financial_entry', 'get_project_document_packet', 'consult_orchestrator'],
    approvalRequiredFor: ['creating or approving labor cost entries', 'marking labor paid'],
    decisionRules: [
      'Labor/sub costs are internal job-cost truth, not customer-facing price unless explicitly used in an estimate.',
      'Separate quoted, approved, invoiced, and paid labor states.',
      'Tie labor costs to documents/crew/sub chats when possible.',
    ],
    output: { cards: ['labor-cost', 'job-cost'] },
  },
  {
    id: 'commission',
    name: 'Sales Commission',
    version: '0.1.0',
    category: 'production',
    status: 'active',
    risk: 'high',
    priority: 74,
    purpose: 'Calculate and track sales commission from saved compensation rules, revenue/payment basis, gross profit, and project financial entries.',
    whenToUse: ['Commission', 'Sales rep payout', 'Rep pay', 'Split', 'How much does sales make?'],
    allowedRoles: ['owner', 'admin', 'office', 'sales', 'system'],
    requiredContext: ['project/customer and commission basis'],
    optionalContext: ['sales rep', 'rate', 'contract amount', 'collected amount', 'gross profit'],
    allowedTools: ['get_project_financial_summary', 'create_project_financial_entry', 'consult_orchestrator'],
    approvalRequiredFor: ['creating, approving, or marking commission paid'],
    decisionRules: [
      'Commission is internal-only unless explicitly shared with an authorized internal user.',
      'Say whether the calculation is based on contract amount, collected revenue, gross profit, or manual override.',
      'Do not finalize commission if compensation rule, collection status, or job cost basis is missing.',
    ],
    output: { cards: ['commission', 'job-cost'] },
  },
  {
    id: 'activity-timeline',
    name: 'Activity Timeline',
    version: '0.1.0',
    category: 'production',
    status: 'active',
    risk: 'low',
    priority: 82,
    purpose: 'Record and explain what happened across chats, uploads, GPS, photos, approvals, tasks, appointments, reports, and project changes.',
    whenToUse: ['What happened last time?', 'Timeline', 'Activity log', 'Recent updates', 'What changed?', 'History'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'project_manager', 'office', 'system'],
    optionalContext: ['customer/project', 'date range', 'activity type', 'actor'],
    allowedTools: ['get_customer_file', 'get_project_document_packet', 'consult_orchestrator'],
    decisionRules: [
      'Ground timeline answers in saved activity/events where available, not chat memory alone.',
      'Separate completed work, failed attempts, pending approvals, and suggested next actions.',
      'GPS/photo/document activity should preserve source context for future AI memory.',
    ],
    output: { cards: ['activity-timeline'] },
    outputFormat: 'Compact timeline card grouped by date/status/source with next-action pills.',
  },
]
