import type { JobroloSkill } from '../types'

export const supplierSkills: JobroloSkill[] = [
  {
    id: 'integration-provider',
    name: 'Integration Provider',
    category: 'suppliers',
    status: 'active',
    risk: 'external',
    priority: 72,
    purpose: 'Check whether outside providers like supplier APIs, Twilio, Google, OpenAI web search, maps, analytics, or storage are configured before promising live external actions.',
    whenToUse: ['Connect ABC', 'SRS API', 'QXO', 'Home Depot', 'Lowe’s', 'Twilio', 'Google reviews', 'web search not working', 'provider missing'],
    allowedRoles: ['owner', 'admin', 'system'],
    allowedTools: ['get_integration_status', 'consult_orchestrator'],
    approvalRequiredFor: ['external provider actions', 'OAuth/API connection changes'],
    decisionRules: [
      'Do not claim live API access unless the provider is configured and healthy.',
      'When an integration is missing, explain the missing provider/API and offer the safest manual fallback.',
      'Provider-specific APIs should go through the integration registry/provider layer, not one-off tools.',
      'Usage-heavy research/search should identify mode/cost risk when possible.',
    ],
    output: { cards: ['integration-readiness'] },
    outputFormat: 'Integration readiness card with configured/missing providers, safe fallback, and connect-next prompts.',
  },
  {
    id: 'price-list',
    name: 'Price List',
    category: 'suppliers',
    status: 'active',
    risk: 'medium',
    priority: 100,
    purpose: 'Review and import supplier material price lists as company-level pricing records.',
    whenToUse: ['Supplier price sheet/list', 'Material prices', 'Show price list', 'Review price rows', 'Import material pricing'],
    whenNotToUse: ['Customer/job estimates or scopes'],
    triggers: { phrases: ['price sheet', 'price list', 'material prices', 'supplier pricing'], fileTypes: ['price_sheet'] },
    allowedRoles: ['owner', 'admin', 'production', 'office', 'system'],
    allowedTools: ['review_price_sheet_items', 'import_price_sheet_items'],
    approvalRequiredFor: ['importing/replacing material pricing'],
    decisionRules: [
      'Price lists are company-level by default, not customer/project files.',
      'Review rows before importing; never clear/replace prices from an ambiguous prompt.',
      'Use review_price_sheet_items for first rows, units, prices, and pending/imported status.',
      'If a live supplier API is not configured, use uploaded price sheets and clearly say the supplier connection is not live yet.',
    ],
    output: { cards: ['price-list'] },
    failureHandling: ['If row data is missing, say the price sheet was detected but rows are not reviewable yet.'],
    tests: ['show price list selects review_price_sheet_items', 'price sheet upload does not need customer/project link'],
  },
  {
    id: 'supplier',
    name: 'Supplier',
    category: 'suppliers',
    status: 'active',
    risk: 'medium',
    priority: 68,
    purpose: 'Represent supplier-specific workflows for ABC, SRS, QXO, and local distributors without adding APIs yet.',
    whenToUse: ['Supplier branch questions', 'Supplier quotes', 'Manual supplier fallback', 'ABC Supply', 'SRS', 'QXO', 'Home Depot', "Lowe's"],
    allowedRoles: ['owner', 'admin', 'production', 'office', 'system'],
    decisionRules: [
      'Do not claim live supplier API access unless configured.',
      'Use manual fallback drafts when supplier integrations are unavailable.',
      'Supplier connections should be implemented through the integration registry/provider layer, not one-off tool calls.',
      'Before placing orders, sending quote requests, or checking account pricing, verify integration readiness and require approval for external actions.',
    ],
    output: { cards: ['integration-readiness'] },
    outputFormat: 'Supplier readiness note with configured/missing provider status, manual fallback, and approval-safe next step.',
  },
  {
    id: 'supplier-invoice',
    name: 'Supplier Invoice',
    category: 'suppliers',
    status: 'active',
    risk: 'medium',
    priority: 72,
    purpose: 'Classify supplier invoices and delivery tickets as job-level cost/delivery documents when a project is known.',
    whenToUse: ['Supplier invoice', 'Delivery ticket', 'Material receipt', 'Job material cost'],
    allowedRoles: ['owner', 'admin', 'production', 'office', 'system'],
    decisionRules: [
      'Supplier invoices/delivery tickets belong to a project/job when job context is identified.',
      'If no job context is known, ask which job or keep in unassigned review.',
      'Do not import supplier invoices into company price lists unless the user explicitly says the document is reusable company pricing.',
      'If invoice content conflicts with user-stated price-list intent, ask one clarification before routing.',
    ],
    output: { cards: ['supplier-invoice', 'job-cost', 'material-order', 'document-file'] },
    outputFormat: 'Supplier invoice/job-cost card with supplier, total if known, linked project candidate, and approval-safe attach/cost actions.',
  },
  {
    id: 'material-ordering',
    name: 'Material Ordering / Delivery',
    category: 'suppliers',
    status: 'experimental',
    risk: 'medium',
    priority: 50,
    purpose: 'Track submitted, scheduled, delivered, backordered, substituted, and invoiced material order states.',
    whenToUse: ['Material order', 'Delivery tracking', 'Backorder', 'Substitution', 'Material status', 'Material drop', 'Supplier order'],
    allowedRoles: ['owner', 'admin', 'production', 'office', 'crew', 'system'],
    decisionRules: [
      'Until integrations exist, ground answers in saved supplier/order/delivery records only.',
      'If no saved supplier/order records exist, say the live supplier connection is not configured instead of guessing.',
    ],
    output: { cards: ['material-order', 'production-status', 'supplier-invoice', 'job-cost'] },
    outputFormat: 'Material readiness note showing saved delivery/order evidence, missing integration status, and next manual check.',
  },
]
