import type { JobroloSkill } from '../types'

export const uploadsDocumentsSkills: JobroloSkill[] = [
  {
    id: 'upload-classifier',
    name: 'Upload Classifier',
    category: 'uploads_documents',
    status: 'active',
    risk: 'medium',
    priority: 100,
    purpose: 'Classify every upload before routing, linking, analysis, or prompt suggestions.',
    whenToUse: ['Every file/photo upload', 'Ambiguous upload routing', 'Upload after a logo/profile/pricing/project discussion'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'crew', 'system'],
    decisionRules: [
      'Classify first; route second.',
      'Use explicit uploadPurpose first, then filename/mime hints, then recent chat context.',
      'If upload route is ambiguous, ask one clear question rather than attaching it to the active customer/project.',
    ],
    failureHandling: ['Upload success means file saved; analysis/linking can still be pending.'],
    tests: ['price sheets route to company pricing', 'logos route to brand assets', 'unknown PDFs route to unassigned review'],
  },
  {
    id: 'upload-status',
    name: 'Upload Status',
    category: 'uploads_documents',
    status: 'active',
    risk: 'low',
    priority: 88,
    purpose: 'Explain upload states clearly: uploading, saved, queued, analyzing, ready, needs review, failed.',
    whenToUse: ['Upload response', 'User asks if document is done', 'Analysis still processing'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'crew', 'system'],
    decisionRules: [
      'Do not say analysis is complete until extraction/analysis result is saved.',
      'If extraction is pending, tell the user it is saved but still processing.',
      'If analysis fails, keep the file saved and surface the failure reason.',
    ],
  },
  {
    id: 'document-type-routing',
    name: 'Document Type Routing',
    category: 'uploads_documents',
    status: 'active',
    risk: 'medium',
    priority: 98,
    purpose: 'Route documents by what they are, not by the currently active chat alone.',
    whenToUse: ['PDF/image/document classification', 'File cards', 'Document review'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'system'],
    decisionRules: [
      'Supplier price lists are company pricing by default.',
      'Templates/agreements are company template library by default unless explicitly job-specific.',
      'Scopes, estimates, carrier docs, inspection reports, signed agreements, and invoices route to customer/project when context is known.',
      'Supplier invoices and delivery tickets route to project/job cost when a job is identified.',
    ],
  },
  {
    id: 'save-scope',
    name: 'Save Scope',
    category: 'uploads_documents',
    status: 'active',
    risk: 'medium',
    priority: 96,
    purpose: 'Save uploaded or pasted scopes/estimates from real extracted/pasted content, never filenames.',
    whenToUse: ['Save scope button', 'Uploaded estimate/scope PDF', 'Pasted scope text'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'system'],
    allowedTools: ['create_scope_from_document', 'create_scope_from_text'],
    decisionRules: [
      'If the source is a saved file/PDF, use create_scope_from_document with documentId.',
      'If the source is pasted text, use create_scope_from_text with raw text.',
      'Never pass a filename, URL, documentId, or placeholder as rawText.',
      'Resolve or create/select a project before claiming the scope is saved.',
    ],
    failureHandling: ['If extracted text is missing or still processing, say the file is saved but scope analysis is not ready yet.'],
  },
  {
    id: 'template-intake',
    name: 'Template Intake',
    category: 'uploads_documents',
    status: 'active',
    risk: 'medium',
    priority: 86,
    purpose: 'Route reusable agreements, estimates, roof reports, invoices, terms, warranties, and signature docs to company template library.',
    whenToUse: ['Template uploads', 'Agreement/contract intake', 'Reusable document questions'],
    allowedRoles: ['owner', 'admin', 'office', 'system'],
    decisionRules: [
      'Reusable templates are company-level unless the user says this exact document belongs to a job.',
      'Ask before turning a customer-signed document into a template.',
    ],
  },
  {
    id: 'file-attachment',
    name: 'File Attachment',
    category: 'uploads_documents',
    status: 'active',
    risk: 'medium',
    priority: 90,
    purpose: 'Attach documents/photos to the correct company, customer, project, claim, report, crew, or partner context.',
    whenToUse: ['Attach file', 'Move/unassign file', 'Show customer files', 'File card actions'],
    allowedRoles: ['owner', 'admin', 'sales', 'production', 'supplement', 'office', 'crew', 'system'],
    allowedTools: ['link_document_to_customer', 'link_document_to_project', 'detach_document_from_customer'],
    approvalRequiredFor: ['destructive deletes', 'external sharing'],
    decisionRules: [
      'Do not require a projectId to attach a file to a customer file.',
      'Do require/resolve a projectId for job-level records like production photos, scopes, reports, and supplier invoices.',
      'Use real document/customer/project IDs from cards/tools, not labels.',
    ],
  },
]
