import { createRequire } from 'node:module'
import { execFileSync } from 'node:child_process'

const require = createRequire(import.meta.url)
const jiti = require('jiti')(process.cwd(), { interopDefault: true })

const { assertSkillRoutingFixtures } = jiti('./src/lib/skills/routing-fixtures.ts')
const { assertSkillRegistryContracts } = jiti('./src/lib/skills/tests/skill-registry.test.ts')
const { assertSkillRoutingContracts } = jiti('./src/lib/skills/tests/skill-routing.test.ts')
const { assertMultiSkillOrchestrationContracts } = jiti('./src/lib/skills/tests/multi-skill-orchestration.test.ts')
const { assertCodyPacketContracts } = jiti('./src/lib/cody/tests/cody-packet.test.ts')
const { assertIntegrationRegistryContracts } = jiti('./src/lib/integrations/tests/integrations.test.ts')
const { assertBrainContextContracts } = jiti('./src/lib/brain/tests/brain-context.test.ts')
const { assertFoundationContextContracts } = jiti('./src/lib/brain/tests/foundation-context.test.ts')
const { assertLocalTruthContracts } = jiti('./src/lib/truth/tests/local-truth.test.ts')
const { assertLocalActionCompilerContracts } = jiti('./src/lib/truth/tests/local-action-compiler.test.ts')
const { assertCardContracts } = jiti('./src/lib/cards/tests/card-contracts.test.ts')
const { assertFieldMapContracts } = jiti('./src/lib/field-map/tests/field-map-contracts.test.ts')
const { assertOfflineFoundationContracts } = jiti('./src/lib/offline/tests/offline-foundation.test.ts')
const { assertPwaContracts } = jiti('./src/lib/offline/tests/pwa-contracts.test.ts')
const { assertOperatingModelContracts } = jiti('./src/lib/operating-models/tests/operating-models.test.ts')

assertCardContracts()
assertFieldMapContracts()
assertOperatingModelContracts()
assertOfflineFoundationContracts()
assertPwaContracts()
assertFoundationContextContracts()
assertBrainContextContracts()
assertSkillRegistryContracts()
assertSkillRoutingFixtures()
assertSkillRoutingContracts()
assertMultiSkillOrchestrationContracts()
assertCodyPacketContracts()
assertIntegrationRegistryContracts()
assertLocalTruthContracts()
assertLocalActionCompilerContracts()
execFileSync(process.execPath, ['scripts/dev-bridge.mjs', 'parser-test'], { stdio: 'inherit' })
console.log('skill routing contracts passed')
